export const GAME_CATALOG = [
  {
    id: 'snake',
    name: 'Neon Snake',
    badge: 'GRID',
    description: 'Slither through a glowing grid and chase higher speeds every time you eat.',
    controls: 'Arrow keys or WASD',
    scoring: '+10 per orb',
    accent: 'from-fuchsia-500/30 via-cyan-400/20 to-blue-500/20',
  },
  {
    id: 'flappy',
    name: 'Pulse Flight',
    badge: 'FLIGHT',
    description: 'Tap to fly between laser pipes while the gap keeps tightening.',
    controls: 'Space or click',
    scoring: '+15 per gate',
    accent: 'from-cyan-500/30 via-blue-500/20 to-fuchsia-500/20',
  },
  {
    id: 'space-shooter',
    name: 'Void Defender',
    badge: 'SHOOTER',
    description: 'Blast neon invaders, clear waves, and hold the line as formations speed up.',
    controls: 'A/D or arrows + space',
    scoring: '+25 per enemy, wave bonus',
    accent: 'from-blue-500/30 via-fuchsia-500/20 to-cyan-400/20',
  },
  {
    id: 'brick-breaker',
    name: 'Photon Breaker',
    badge: 'BREAK',
    description: 'Shatter glass bricks and survive longer volleys with faster rebounds.',
    controls: 'Mouse or arrows',
    scoring: '+100 per brick',
    accent: 'from-pink-500/30 via-violet-500/20 to-cyan-500/20',
  },
  {
    id: 'reaction-clicker',
    name: 'Reflex Rush',
    badge: 'REFLEX',
    description: 'Wait for the flash, click instantly, and keep pace as the windows shrink.',
    controls: 'Mouse or tap',
    scoring: 'Faster clicks = more points',
    accent: 'from-cyan-400/30 via-pink-500/20 to-purple-500/20',
  },
  {
    id: 'endless-runner',
    name: 'Neon Runner',
    badge: 'RUNNER',
    description: 'Vault over obstacles and survive long enough for the cityscape to accelerate.',
    controls: 'Space, up arrow, or tap',
    scoring: 'Distance score',
    accent: 'from-purple-500/30 via-blue-500/20 to-cyan-400/20',
  },
  {
    id: 'memory-flip',
    name: 'Echo Flip',
    badge: 'MEMORY',
    description: 'Match glowing cards, keep your streak alive, and climb through tougher layouts.',
    controls: 'Mouse or tap',
    scoring: '+80 per match',
    accent: 'from-fuchsia-500/30 via-blue-500/20 to-cyan-500/20',
  },
  {
    id: 'whack-a-mole',
    name: 'Cyber Whack',
    badge: 'WHACK',
    description: 'Crush popping glitches before they blink away and the tempo spikes.',
    controls: 'Mouse or tap',
    scoring: '+10 per hit',
    accent: 'from-cyan-500/30 via-purple-500/20 to-pink-500/20',
  },
  {
    id: 'typing-speed',
    name: 'Type Surge',
    badge: 'TYPE',
    description: 'Burn through word chains with combo scoring and increasingly harder vocabulary.',
    controls: 'Keyboard + enter',
    scoring: '+20 per word',
    accent: 'from-blue-500/30 via-cyan-400/20 to-pink-500/20',
  },
];

export function getGameById(gameId) {
  return GAME_CATALOG.find((game) => game.id === gameId);
}
