export const GAME_CATALOG = [
  {
    id: 'snake',
    name: 'Neon Snake',
    badge: 'GRID',
    description: 'Slither through a glowing grid and chase higher speeds every time you eat.',
    controls: 'Arrow keys or WASD',
    scoring: '+10 per orb',
    instructions: 'Steer around the arena, eat glowing orbs, and avoid your own trail as the snake speeds up.',
    accent: 'from-fuchsia-500/30 via-cyan-400/20 to-blue-500/20',
  },
  {
    id: 'flappy',
    name: 'Pulse Flight',
    badge: 'FLIGHT',
    description: 'Tap to fly between laser pipes while the gap keeps tightening.',
    controls: 'Space or click',
    scoring: '+15 per gate',
    instructions: 'Tap or press space to stay airborne and thread every shrinking gate without clipping a pipe.',
    accent: 'from-cyan-500/30 via-blue-500/20 to-fuchsia-500/20',
  },
  {
    id: 'space-shooter',
    name: 'Void Defender',
    badge: 'SHOOTER',
    description: 'Survive a steadier enemy ramp, collect support powerups, and outlast each mini-boss push.',
    controls: 'A/D or arrows + space',
    scoring: 'Survival score + enemy kills',
    instructions: 'You have a short grace period at the start. Move left or right, shoot with space, grab health, shield, rapid-fire, and screen-clear powerups, and survive as the threat rises linearly.',
    accent: 'from-blue-500/30 via-fuchsia-500/20 to-cyan-400/20',
  },
  {
    id: 'brick-breaker',
    name: 'Photon Breaker',
    badge: 'BREAK',
    description: 'Break durable bricks, catch powerups, and juggle multiple balls as speed builds.',
    controls: 'Mouse movement only',
    scoring: '+100 per brick, powerup bonus',
    instructions: 'Guide the paddle with your mouse, catch powerups, and keep every ball alive as the rebounds get faster.',
    accent: 'from-pink-500/30 via-violet-500/20 to-cyan-500/20',
  },
  {
    id: 'reaction-clicker',
    name: 'Reflex Rush',
    badge: 'REFLEX',
    description: 'Endless reaction mode: keep clicking on green, score from speed, and survive until mistakes run out.',
    controls: 'Mouse or tap',
    scoring: 'Successful reactions + speed bonus',
    instructions: 'Wait for the target to turn green, react as fast as possible, and keep going until you run out of mistakes or miss the shrinking window.',
    accent: 'from-cyan-400/30 via-pink-500/20 to-purple-500/20',
  },
  {
    id: 'endless-runner',
    name: 'Neon Runner',
    badge: 'RUNNER',
    description: 'Jump obstacles, chain powerups, and survive the faster city with shield and double-score runs.',
    controls: 'Space, up arrow, or tap',
    scoring: 'Distance score',
    instructions: 'Jump incoming hazards, grab shield, speed, and double-score powerups, and keep your distance climbing constantly.',
    accent: 'from-purple-500/30 via-blue-500/20 to-cyan-400/20',
  },
  {
    id: 'memory-flip',
    name: 'Echo Flip',
    badge: 'MEMORY',
    description: 'Match glowing cards, keep your streak alive, and climb through tougher layouts.',
    controls: 'Mouse or tap',
    scoring: '+80 per match',
    instructions: 'Memorize the cards, reveal matching pairs, and beat the timer before each tougher layout appears.',
    accent: 'from-fuchsia-500/30 via-blue-500/20 to-cyan-500/20',
  },
  {
    id: 'typing-speed',
    name: 'Type Surge',
    badge: 'TYPE',
    description: 'Type through a much larger word pool with longer prompts and faster scoring pressure.',
    controls: 'Keyboard + enter',
    scoring: 'Word length + streak bonus',
    instructions: 'Type the prompt exactly, press Enter, and handle longer words as difficulty ramps up.',
    accent: 'from-blue-500/30 via-cyan-400/20 to-pink-500/20',
  },
];

export function getGameById(gameId) {
  return GAME_CATALOG.find((game) => game.id === gameId);
}
